// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MyMvcExamProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250407184532_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MyMvcExamProject.Models.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Options");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCorrect = true,
                            QuestionId = 1,
                            Text = "Para kazanmak"
                        },
                        new
                        {
                            Id = 2,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "Arkadaş bulmak"
                        },
                        new
                        {
                            Id = 3,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "Macera yaşamak"
                        },
                        new
                        {
                            Id = 4,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "Okula gitmek"
                        },
                        new
                        {
                            Id = 5,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "Yalan söylediği için"
                        },
                        new
                        {
                            Id = 6,
                            IsCorrect = true,
                            QuestionId = 2,
                            Text = "Güçlü ama zihinsel engelli olduğu için"
                        },
                        new
                        {
                            Id = 7,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "Hırsızlık yaptığı için"
                        },
                        new
                        {
                            Id = 8,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "George'u kıskandığı için"
                        },
                        new
                        {
                            Id = 9,
                            IsCorrect = true,
                            QuestionId = 3,
                            Text = "Büyük bir çiftlik kurmak"
                        },
                        new
                        {
                            Id = 10,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "Yazın okula gitmek"
                        },
                        new
                        {
                            Id = 11,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "Zengin olmak"
                        },
                        new
                        {
                            Id = 12,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "Tatile gitmek"
                        },
                        new
                        {
                            Id = 13,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "Çiftlikteki diğer işçilerin tavrı"
                        },
                        new
                        {
                            Id = 14,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "Lennie'nin zihinsel engeli"
                        },
                        new
                        {
                            Id = 15,
                            IsCorrect = true,
                            QuestionId = 4,
                            Text = "George'un arkadaşlık anlayışı"
                        },
                        new
                        {
                            Id = 16,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "Çiftlik işlerinin zor olması"
                        },
                        new
                        {
                            Id = 17,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "Zenginleşme ve güç kazanma"
                        },
                        new
                        {
                            Id = 18,
                            IsCorrect = true,
                            QuestionId = 5,
                            Text = "Huzurlu bir yaşam kurma"
                        },
                        new
                        {
                            Id = 19,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "Büyük bir çiftlik kurma"
                        },
                        new
                        {
                            Id = 20,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "Görkemli bir ev inşa etme"
                        },
                        new
                        {
                            Id = 21,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "Çevresindeki insanlara zarar vermek"
                        },
                        new
                        {
                            Id = 22,
                            IsCorrect = true,
                            QuestionId = 6,
                            Text = "Zihinsel engelinin kontrolsüz bir şekilde ortaya çıkması"
                        },
                        new
                        {
                            Id = 23,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "Gözyaşlarını tutamaması"
                        },
                        new
                        {
                            Id = 24,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "Başka insanları kıskanması"
                        },
                        new
                        {
                            Id = 25,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "Yeni insanlar tanımak"
                        },
                        new
                        {
                            Id = 26,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "Büyük bir çiftlikte çalışmak"
                        },
                        new
                        {
                            Id = 27,
                            IsCorrect = false,
                            QuestionId = 7,
                            Text = "Güvenli bir yaşam sürmek"
                        },
                        new
                        {
                            Id = 28,
                            IsCorrect = true,
                            QuestionId = 7,
                            Text = "Kendi çiftliklerine sahip olmak"
                        },
                        new
                        {
                            Id = 29,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Onun adına parayı almak"
                        },
                        new
                        {
                            Id = 30,
                            IsCorrect = true,
                            QuestionId = 8,
                            Text = "Ona güvenmek ve korumak"
                        },
                        new
                        {
                            Id = 31,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Başka insanlara yardım etmek"
                        },
                        new
                        {
                            Id = 32,
                            IsCorrect = false,
                            QuestionId = 8,
                            Text = "Kendi çıkarlarını savunmak"
                        },
                        new
                        {
                            Id = 33,
                            IsCorrect = true,
                            QuestionId = 9,
                            Text = "Düşünmeden hareket etmesi"
                        },
                        new
                        {
                            Id = 34,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "Çevresindeki insanları sevmesi"
                        },
                        new
                        {
                            Id = 35,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "George'a duyduğu hayranlık"
                        },
                        new
                        {
                            Id = 36,
                            IsCorrect = false,
                            QuestionId = 9,
                            Text = "Kendi gücünü fark etmesi"
                        },
                        new
                        {
                            Id = 37,
                            IsCorrect = false,
                            QuestionId = 10,
                            Text = "Bir başkasına zarar vermek"
                        },
                        new
                        {
                            Id = 38,
                            IsCorrect = true,
                            QuestionId = 10,
                            Text = "Lennie'nin yanlış anlaması"
                        },
                        new
                        {
                            Id = 39,
                            IsCorrect = false,
                            QuestionId = 10,
                            Text = "Çiftlikteki diğer işçilerin sorumsuzluğu"
                        },
                        new
                        {
                            Id = 40,
                            IsCorrect = false,
                            QuestionId = 10,
                            Text = "Çiftlik yöneticisinin cezalandırması"
                        });
                });

            modelBuilder.Entity("MyMvcExamProject.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CorrectOptionIndex")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrectOptionIndex = 0,
                            Text = "George ve Lennie'nin çiftlikte çalışmaya gitme amacı nedir?"
                        },
                        new
                        {
                            Id = 2,
                            CorrectOptionIndex = 1,
                            Text = "Lennie neden başlarını belaya sokar?"
                        },
                        new
                        {
                            Id = 3,
                            CorrectOptionIndex = 0,
                            Text = "Lennie'nin en büyük hayali nedir?"
                        },
                        new
                        {
                            Id = 4,
                            CorrectOptionIndex = 2,
                            Text = "George, Lennie ile ilgili ne kadar endişelenmektedir?"
                        },
                        new
                        {
                            Id = 5,
                            CorrectOptionIndex = 0,
                            Text = "Çiftlikte çalışmak isteyenlerin motivasyonu nedir?"
                        },
                        new
                        {
                            Id = 6,
                            CorrectOptionIndex = 1,
                            Text = "Lennie'nin başına gelen olaylar neden genellikle trajik sonuçlanır?"
                        },
                        new
                        {
                            Id = 7,
                            CorrectOptionIndex = 3,
                            Text = "George ve Lennie'nin hayalini paylaştığı çiftlikte ne tür bir hayat yaşamayı planlarlar?"
                        },
                        new
                        {
                            Id = 8,
                            CorrectOptionIndex = 2,
                            Text = "George, Lennie'yi hangi durumlarda savunur?"
                        },
                        new
                        {
                            Id = 9,
                            CorrectOptionIndex = 0,
                            Text = "Lennie'nin zihinsel engelli olmasının etkileri nelerdir?"
                        },
                        new
                        {
                            Id = 10,
                            CorrectOptionIndex = 3,
                            Text = "Hangi olay, George'un Lennie'yi öldürmesini zorunlu kılar?"
                        });
                });

            modelBuilder.Entity("MyMvcExamProject.Models.Option", b =>
                {
                    b.HasOne("MyMvcExamProject.Models.Question", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyMvcExamProject.Models.Question", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
